# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 08:50
from __future__ import unicode_literals

import accounts.models
import accounts.validation
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20170611_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_title', models.CharField(help_text='Max 60 character allowed.', max_length=60)),
                ('e_date', models.DateField(default=None)),
                ('e_time', models.TimeField(default=None)),
                ('e_age_min', models.IntegerField(default=0)),
                ('e_age_max', models.IntegerField(default=100)),
                ('e_location', models.CharField(default='Bangalore', max_length=100)),
                ('e_details', models.TextField(blank=True)),
                ('e_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=accounts.models.upload_image, validators=[accounts.validation.image_extension])),
                ('e_active', models.BooleanField(default=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('e_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Category')),
                ('e_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SubCategory')),
                ('e_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('j_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('j_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
