# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 11:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_title', models.CharField(max_length=250)),
                ('p_date', models.DateField(default=None)),
                ('p_time', models.TimeField(default=None)),
                ('p_veg', models.BooleanField(default=True, verbose_name='Veg/Non-Veg')),
                ('p_active', models.BooleanField(default=True)),
                ('p_details', models.TextField(blank=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('p_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Posted by')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
