# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170610_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdxuser',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rdxuser',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
