# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170611_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdxuser',
            name='dob',
        ),
        migrations.AddField(
            model_name='rdxuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
